<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = array(
            array('code' => 'AD', 'name' => '{"ar": "أندورا", "en": "Andorra"}', 'nationality' => '{"ar": "أندوري", "en": "Andorran"}', 'dial_code' => '+376'),
            array('code' => 'AE', 'name' => '{"ar": "الإمارات العربية المتحدة", "en": "United Arab Emirates"}', 'nationality' => '{"ar": "إماراتي", "en": "Emirati"}', 'dial_code' => '+971'),
            array('code' => 'AF', 'name' => '{"ar": "أفغانستان", "en": "Afghanistan"}', 'nationality' => '{"ar": "أفغانستاني", "en": "Afghan"}', 'dial_code' => '+93'),
            array('code' => 'AG', 'name' => '{"ar": "أنتيغوا وبربودا", "en": "Antigua and Barbuda"}', 'nationality' => '{"ar": "بربودي", "en": "Antiguan"}', 'dial_code' => '+1268'),
            array('code' => 'AI', 'name' => '{"ar": "أنغويلا", "en": "Anguilla"}', 'nationality' => '{"ar": "أنغويلي", "en": "Anguillan"}', 'dial_code' => '+1264'),
            array('code' => 'AL', 'name' => '{"ar": "ألبانيا", "en": "Albania"}', 'nationality' => '{"ar": "ألباني", "en": "Albanian"}', 'dial_code' => '+355'),
            array('code' => 'AM', 'name' => '{"ar": "أرمينيا", "en": "Armenia"}', 'nationality' => '{"ar": "أرميني", "en": "Armenian"}', 'dial_code' => '+374'),
            array('code' => 'AN', 'name' => '{"ar": "جزر الأنتيل الهولندي", "en": "Netherlands Antilles"}', 'nationality' => '{"ar": "هولندي", "en": "Dutch Antilier"}', 'dial_code' => '+599'),
            array('code' => 'AO', 'name' => '{"ar": "أنغولا", "en": "Angola"}', 'nationality' => '{"ar": "أنقولي", "en": "Angolan"}', 'dial_code' => '+244'),
            array('code' => 'AQ', 'name' => '{"ar": "أنتاركتيكا", "en": "Antarctica"}', 'nationality' => '{"ar": "أنتاركتيكي", "en": "Antarctican"}', 'dial_code' => '+672'),
            array('code' => 'AR', 'name' => '{"ar": "الأرجنتين", "en": "Argentina"}', 'nationality' => '{"ar": "أرجنتيني", "en": "Argentinian"}', 'dial_code' => '+54'),
            array('code' => 'AS', 'name' => '{"ar": "ساموا-الأمريكي", "en": "American Samoa"}', 'nationality' => '{"ar": "أمريكي سامواني", "en": "American Samoan"}', 'dial_code' => '+1684'),
            array('code' => 'AT', 'name' => '{"ar": "النمسا", "en": "Austria"}', 'nationality' => '{"ar": "نمساوي", "en": "Austrian"}', 'dial_code' => '+43'),
            array('code' => 'AU', 'name' => '{"ar": "أستراليا", "en": "Australia"}', 'nationality' => '{"ar": "أسترالي", "en": "Australian"}', 'dial_code' => '+61'),
            array('code' => 'AW', 'name' => '{"ar": "أروبه", "en": "Aruba"}', 'nationality' => '{"ar": "أوروبهيني", "en": "Aruban"}', 'dial_code' => '+297'),
            array('code' => 'AX', 'name' => '{"ar": "جزر آلاند", "en": "Aland Islands"}', 'nationality' => '{"ar": "آلاندي", "en": "Aland Islander"}', 'dial_code' => '+ '),
            array('code' => 'AZ', 'name' => '{"ar": "أذربيجان", "en": "Azerbaijan"}', 'nationality' => '{"ar": "أذربيجاني", "en": "Azerbaijani"}', 'dial_code' => '+994'),
            array('code' => 'BA', 'name' => '{"ar": "البوسنة و الهرسك", "en": "Bosnia and Herzegovina"}', 'nationality' => '{"ar": "بوسني/هرسكي", "en": "Bosnian / Herzegovinian"}', 'dial_code' => '+387'),
            array('code' => 'BB', 'name' => '{"ar": "بربادوس", "en": "Barbados"}', 'nationality' => '{"ar": "بربادوسي", "en": "Barbadian"}', 'dial_code' => '+1246'),
            array('code' => 'BD', 'name' => '{"ar": "بنغلاديش", "en": "Bangladesh"}', 'nationality' => '{"ar": "بنغلاديشي", "en": "Bangladeshi"}', 'dial_code' => '+880'),
            array('code' => 'BE', 'name' => '{"ar": "بلجيكا", "en": "Belgium"}', 'nationality' => '{"ar": "بلجيكي", "en": "Belgian"}', 'dial_code' => '+32'),
            array('code' => 'BF', 'name' => '{"ar": "بوركينا فاسو", "en": "Burkina Faso"}', 'nationality' => '{"ar": "بوركيني", "en": "Burkinabe"}', 'dial_code' => '+226'),
            array('code' => 'BG', 'name' => '{"ar": "بلغاريا", "en": "Bulgaria"}', 'nationality' => '{"ar": "بلغاري", "en": "Bulgarian"}', 'dial_code' => '+359'),
            array('code' => 'BH', 'name' => '{"ar": "البحرين", "en": "Bahrain"}', 'nationality' => '{"ar": "بحريني", "en": "Bahraini"}', 'dial_code' => '+973'),
            array('code' => 'BI', 'name' => '{"ar": "بوروندي", "en": "Burundi"}', 'nationality' => '{"ar": "بورونيدي", "en": "Burundian"}', 'dial_code' => '+257'),
            array('code' => 'BJ', 'name' => '{"ar": "بنين", "en": "Benin"}', 'nationality' => '{"ar": "بنيني", "en": "Beninese"}', 'dial_code' => '+229'),
            array('code' => 'BL', 'name' => '{"ar": "سان بارتيلمي", "en": "Saint Barthelemy"}', 'nationality' => '{"ar": "سان بارتيلمي", "en": "Saint Barthelmian"}', 'dial_code' => '+590'),
            array('code' => 'BM', 'name' => '{"ar": "جزر برمودا", "en": "Bermuda"}', 'nationality' => '{"ar": "برمودي", "en": "Bermudan"}', 'dial_code' => '+1441'),
            array('code' => 'BN', 'name' => '{"ar": "بروني", "en": "Brunei Darussalam"}', 'nationality' => '{"ar": "بروني", "en": "Bruneian"}', 'dial_code' => '+673'),
            array('code' => 'BO', 'name' => '{"ar": "بوليفيا", "en": "Bolivia"}', 'nationality' => '{"ar": "بوليفي", "en": "Bolivian"}', 'dial_code' => '+591'),
            array('code' => 'BR', 'name' => '{"ar": "البرازيل", "en": "Brazil"}', 'nationality' => '{"ar": "برازيلي", "en": "Brazilian"}', 'dial_code' => '+55'),
            array('code' => 'BS', 'name' => '{"ar": "الباهاماس", "en": "Bahamas"}', 'nationality' => '{"ar": "باهاميسي", "en": "Bahamian"}', 'dial_code' => '+1242'),
            array('code' => 'BT', 'name' => '{"ar": "بوتان", "en": "Bhutan"}', 'nationality' => '{"ar": "بوتاني", "en": "Bhutanese"}', 'dial_code' => '+975'),
            array('code' => 'BV', 'name' => '{"ar": "جزيرة بوفيه", "en": "Bouvet Island"}', 'nationality' => '{"ar": "بوفيهي", "en": "Bouvetian"}', 'dial_code' => '+ '),
            array('code' => 'BW', 'name' => '{"ar": "بوتسوانا", "en": "Botswana"}', 'nationality' => '{"ar": "بوتسواني", "en": "Botswanan"}', 'dial_code' => '+267'),
            array('code' => 'BY', 'name' => '{"ar": "روسيا البيضاء", "en": "Belarus"}', 'nationality' => '{"ar": "روسي", "en": "Belarusian"}', 'dial_code' => '+375'),
            array('code' => 'BZ', 'name' => '{"ar": "بيليز", "en": "Belize"}', 'nationality' => '{"ar": "بيليزي", "en": "Belizean"}', 'dial_code' => '+501'),
            array('code' => 'CA', 'name' => '{"ar": "كندا", "en": "Canada"}', 'nationality' => '{"ar": "كندي", "en": "Canadian"}', 'dial_code' => '+1'),
            array('code' => 'CC', 'name' => '{"ar": "جزر كوكوس", "en": "Cocos (Keeling) Islands"}', 'nationality' => '{"ar": "جزر كوكوس", "en": "Cocos Islander"}', 'dial_code' => '+61'),
            array('code' => 'CF', 'name' => '{"ar": "جمهورية أفريقيا الوسطى", "en": "Central African Republic"}', 'nationality' => '{"ar": "أفريقي", "en": "Central African"}', 'dial_code' => '+236'),
            array('code' => 'CG', 'name' => '{"ar": "الكونغو", "en": "Congo"}', 'nationality' => '{"ar": "كونغي", "en": "Congolese"}', 'dial_code' => '+242'),
            array('code' => 'CH', 'name' => '{"ar": "سويسرا", "en": "Switzerland"}', 'nationality' => '{"ar": "سويسري", "en": "Swiss"}', 'dial_code' => '+41'),
            array('code' => 'CI', 'name' => '{"ar": "ساحل العاج", "en": "Ivory Coast"}', 'nationality' => '{"ar": "ساحل العاج", "en": "Ivory Coastian"}', 'dial_code' => '+225'),
            array('code' => 'CK', 'name' => '{"ar": "جزر كوك", "en": "Cook Islands"}', 'nationality' => '{"ar": "جزر كوك", "en": "Cook Islander"}', 'dial_code' => '+682'),
            array('code' => 'CL', 'name' => '{"ar": "شيلي", "en": "Chile"}', 'nationality' => '{"ar": "شيلي", "en": "Chilean"}', 'dial_code' => '+56'),
            array('code' => 'CM', 'name' => '{"ar": "كاميرون", "en": "Cameroon"}', 'nationality' => '{"ar": "كاميروني", "en": "Cameroonian"}', 'dial_code' => '+237'),
            array('code' => 'CN', 'name' => '{"ar": "الصين", "en": "China"}', 'nationality' => '{"ar": "صيني", "en": "Chinese"}', 'dial_code' => '+86'),
            array('code' => 'CO', 'name' => '{"ar": "كولومبيا", "en": "Colombia"}', 'nationality' => '{"ar": "كولومبي", "en": "Colombian"}', 'dial_code' => '+57'),
            array('code' => 'CR', 'name' => '{"ar": "كوستاريكا", "en": "Costa Rica"}', 'nationality' => '{"ar": "كوستاريكي", "en": "Costa Rican"}', 'dial_code' => '+506'),
            array('code' => 'CU', 'name' => '{"ar": "كوبا", "en": "Cuba"}', 'nationality' => '{"ar": "كوبي", "en": "Cuban"}', 'dial_code' => '+53'),
            array('code' => 'CV', 'name' => '{"ar": "الرأس الأخضر", "en": "Cape Verde"}', 'nationality' => '{"ar": "الرأس الأخضر", "en": "Cape Verdean"}', 'dial_code' => '+238'),
            array('code' => 'CW', 'name' => '{"ar": "كوراساو", "en": "Curaçao"}', 'nationality' => '{"ar": "كوراساوي", "en": "Curacian"}', 'dial_code' => '+ '),
            array('code' => 'CX', 'name' => '{"ar": "جزيرة عيد الميلاد", "en": "Christmas Island"}', 'nationality' => '{"ar": "جزيرة عيد الميلاد", "en": "Christmas Islander"}', 'dial_code' => '+61'),
            array('code' => 'CY', 'name' => '{"ar": "قبرص", "en": "Cyprus"}', 'nationality' => '{"ar": "قبرصي", "en": "Cypriot"}', 'dial_code' => '+357'),
            array('code' => 'CZ', 'name' => '{"ar": "الجمهورية التشيكية", "en": "Czech Republic"}', 'nationality' => '{"ar": "تشيكي", "en": "Czech"}', 'dial_code' => '+420'),
            array('code' => 'DE', 'name' => '{"ar": "ألمانيا", "en": "Germany"}', 'nationality' => '{"ar": "ألماني", "en": "German"}', 'dial_code' => '+49'),
            array('code' => 'DJ', 'name' => '{"ar": "جيبوتي", "en": "Djibouti"}', 'nationality' => '{"ar": "جيبوتي", "en": "Djiboutian"}', 'dial_code' => '+253'),
            array('code' => 'DK', 'name' => '{"ar": "الدانمارك", "en": "Denmark"}', 'nationality' => '{"ar": "دنماركي", "en": "Danish"}', 'dial_code' => '+45'),
            array('code' => 'DM', 'name' => '{"ar": "دومينيكا", "en": "Dominica"}', 'nationality' => '{"ar": "دومينيكي", "en": "Dominican"}', 'dial_code' => '+1767'),
            array('code' => 'DO', 'name' => '{"ar": "الجمهورية الدومينيكية", "en": "Dominican Republic"}', 'nationality' => '{"ar": "دومينيكي", "en": "Dominican"}', 'dial_code' => '+1809'),
            array('code' => 'DZ', 'name' => '{"ar": "الجزائر", "en": "Algeria"}', 'nationality' => '{"ar": "جزائري", "en": "Algerian"}', 'dial_code' => '+213'),
            array('code' => 'EC', 'name' => '{"ar": "إكوادور", "en": "Ecuador"}', 'nationality' => '{"ar": "إكوادوري", "en": "Ecuadorian"}', 'dial_code' => '+593'),
            array('code' => 'EE', 'name' => '{"ar": "استونيا", "en": "Estonia"}', 'nationality' => '{"ar": "استوني", "en": "Estonian"}', 'dial_code' => '+372'),
            array('code' => 'EG', 'name' => '{"ar": "مصر", "en": "Egypt"}', 'nationality' => '{"ar": "مصري", "en": "Egyptian"}', 'dial_code' => '+20'),
            array('code' => 'EH', 'name' => '{"ar": "الصحراء الغربية", "en": "Western Sahara"}', 'nationality' => '{"ar": "صحراوي", "en": "Sahrawian"}', 'dial_code' => '+ '),
            array('code' => 'ER', 'name' => '{"ar": "إريتريا", "en": "Eritrea"}', 'nationality' => '{"ar": "إريتيري", "en": "Eritrean"}', 'dial_code' => '+291'),
            array('code' => 'ES', 'name' => '{"ar": "إسبانيا", "en": "Spain"}', 'nationality' => '{"ar": "إسباني", "en": "Spanish"}', 'dial_code' => '+34'),
            array('code' => 'ET', 'name' => '{"ar": "أثيوبيا", "en": "Ethiopia"}', 'nationality' => '{"ar": "أثيوبي", "en": "Ethiopian"}', 'dial_code' => '+251'),
            array('code' => 'FI', 'name' => '{"ar": "فنلندا", "en": "Finland"}', 'nationality' => '{"ar": "فنلندي", "en": "Finnish"}', 'dial_code' => '+358'),
            array('code' => 'FJ', 'name' => '{"ar": "فيجي", "en": "Fiji"}', 'nationality' => '{"ar": "فيجي", "en": "Fijian"}', 'dial_code' => '+679'),
            array('code' => 'FK', 'name' => '{"ar": "جزر فوكلاند", "en": "Falkland Islands (Malvinas)"}', 'nationality' => '{"ar": "فوكلاندي", "en": "Falkland Islander"}', 'dial_code' => '+500'),
            array('code' => 'FM', 'name' => '{"ar": "مايكرونيزيا", "en": "Micronesia"}', 'nationality' => '{"ar": "مايكرونيزيي", "en": "Micronesian"}', 'dial_code' => '+691'),
            array('code' => 'FO', 'name' => '{"ar": "جزر فارو", "en": "Faroe Islands"}', 'nationality' => '{"ar": "جزر فارو", "en": "Faroese"}', 'dial_code' => '+298'),
            array('code' => 'FR', 'name' => '{"ar": "فرنسا", "en": "France"}', 'nationality' => '{"ar": "فرنسي", "en": "French"}', 'dial_code' => '+33'),
            array('code' => 'GA', 'name' => '{"ar": "الغابون", "en": "Gabon"}', 'nationality' => '{"ar": "غابوني", "en": "Gabonese"}', 'dial_code' => '+241'),
            array('code' => 'GB', 'name' => '{"ar": "المملكة المتحدة", "en": "United Kingdom"}', 'nationality' => '{"ar": "بريطاني", "en": "British"}', 'dial_code' => '+44'),
            array('code' => 'GD', 'name' => '{"ar": "غرينادا", "en": "Grenada"}', 'nationality' => '{"ar": "غرينادي", "en": "Grenadian"}', 'dial_code' => '+1473'),
            array('code' => 'GE', 'name' => '{"ar": "جيورجيا", "en": "Georgia"}', 'nationality' => '{"ar": "جيورجي", "en": "Georgian"}', 'dial_code' => '+995'),
            array('code' => 'GF', 'name' => '{"ar": "غويانا الفرنسية", "en": "French Guiana"}', 'nationality' => '{"ar": "غويانا الفرنسية", "en": "French Guianese"}', 'dial_code' => '+ '),
            array('code' => 'GG', 'name' => '{"ar": "غيرنزي", "en": "Guernsey"}', 'nationality' => '{"ar": "غيرنزي", "en": "Guernsian"}', 'dial_code' => '+ '),
            array('code' => 'GH', 'name' => '{"ar": "غانا", "en": "Ghana"}', 'nationality' => '{"ar": "غاني", "en": "Ghanaian"}', 'dial_code' => '+233'),
            array('code' => 'GI', 'name' => '{"ar": "جبل طارق", "en": "Gibraltar"}', 'nationality' => '{"ar": "جبل طارق", "en": "Gibraltar"}', 'dial_code' => '+350'),
            array('code' => 'GL', 'name' => '{"ar": "جرينلاند", "en": "Greenland"}', 'nationality' => '{"ar": "جرينلاندي", "en": "Greenlandic"}', 'dial_code' => '+299'),
            array('code' => 'GM', 'name' => '{"ar": "غامبيا", "en": "Gambia"}', 'nationality' => '{"ar": "غامبي", "en": "Gambian"}', 'dial_code' => '+220'),
            array('code' => 'GN', 'name' => '{"ar": "غينيا", "en": "Guinea"}', 'nationality' => '{"ar": "غيني", "en": "Guinean"}', 'dial_code' => '+224'),
            array('code' => 'GP', 'name' => '{"ar": "جزر جوادلوب", "en": "Guadeloupe"}', 'nationality' => '{"ar": "جزر جوادلوب", "en": "Guadeloupe"}', 'dial_code' => '+ '),
            array('code' => 'GQ', 'name' => '{"ar": "غينيا الاستوائي", "en": "Equatorial Guinea"}', 'nationality' => '{"ar": "غيني", "en": "Equatorial Guinean"}', 'dial_code' => '+240'),
            array('code' => 'GR', 'name' => '{"ar": "اليونان", "en": "Greece"}', 'nationality' => '{"ar": "يوناني", "en": "Greek"}', 'dial_code' => '+30'),
            array('code' => 'GS', 'name' => '{"ar": "المنطقة القطبية الجنوبية", "en": "South Georgia and the South Sandwich"}', 'nationality' => '{"ar": "لمنطقة القطبية الجنوبية", "en": "South Georgia and the South Sandwich"}', 'dial_code' => '+ '),
            array('code' => 'GT', 'name' => '{"ar": "غواتيمال", "en": "Guatemala"}', 'nationality' => '{"ar": "غواتيمالي", "en": "Guatemalan"}', 'dial_code' => '+502'),
            array('code' => 'GU', 'name' => '{"ar": "جوام", "en": "Guam"}', 'nationality' => '{"ar": "جوامي", "en": "Guamanian"}', 'dial_code' => '+1671'),
            array('code' => 'GW', 'name' => '{"ar": "غينيا-بيساو", "en": "Guinea-Bissau"}', 'nationality' => '{"ar": "غيني", "en": "Guinea-Bissauan"}', 'dial_code' => '+245'),
            array('code' => 'GY', 'name' => '{"ar": "غيانا", "en": "Guyana"}', 'nationality' => '{"ar": "غياني", "en": "Guyanese"}', 'dial_code' => '+592'),
            array('code' => 'HK', 'name' => '{"ar": "هونغ كونغ", "en": "Hong Kong"}', 'nationality' => '{"ar": "هونغ كونغي", "en": "Hongkongese"}', 'dial_code' => '+852'),
            array('code' => 'HM', 'name' => '{"ar": "جزيرة هيرد وجزر ماكدونالد", "en": "Heard and Mc Donald Islands"}', 'nationality' => '{"ar": "جزيرة هيرد وجزر ماكدونالد", "en": "Heard and Mc Donald Islanders"}', 'dial_code' => '+ '),
            array('code' => 'HN', 'name' => '{"ar": "هندوراس", "en": "Honduras"}', 'nationality' => '{"ar": "هندوراسي", "en": "Honduran"}', 'dial_code' => '+504'),
            array('code' => 'HR', 'name' => '{"ar": "كرواتيا", "en": "Croatia"}', 'nationality' => '{"ar": "كوراتي", "en": "Croatian"}', 'dial_code' => '+385'),
            array('code' => 'HT', 'name' => '{"ar": "هايتي", "en": "Haiti"}', 'nationality' => '{"ar": "هايتي", "en": "Haitian"}', 'dial_code' => '+509'),
            array('code' => 'HU', 'name' => '{"ar": "المجر", "en": "Hungary"}', 'nationality' => '{"ar": "مجري", "en": "Hungarian"}', 'dial_code' => '+36'),
            array('code' => 'ID', 'name' => '{"ar": "أندونيسيا", "en": "Indonesia"}', 'nationality' => '{"ar": "أندونيسيي", "en": "Indonesian"}', 'dial_code' => '+62'),
            array('code' => 'IE', 'name' => '{"ar": "إيرلندا", "en": "Ireland"}', 'nationality' => '{"ar": "إيرلندي", "en": "Irish"}', 'dial_code' => '+353'),
            array('code' => 'IL', 'name' => '{"ar": "إسرائيل", "en": "Israel"}', 'nationality' => '{"ar": "إسرائيلي", "en": "Israeli"}', 'dial_code' => '+972'),
            array('code' => 'IM', 'name' => '{"ar": "جزيرة مان", "en": "Isle of Man"}', 'nationality' => '{"ar": "ماني", "en": "Manx"}', 'dial_code' => '+44'),
            array('code' => 'IN', 'name' => '{"ar": "الهند", "en": "India"}', 'nationality' => '{"ar": "هندي", "en": "Indian"}', 'dial_code' => '+91'),
            array('code' => 'IO', 'name' => '{"ar": "إقليم المحيط الهندي البريطاني", "en": "British Indian Ocean Territory"}', 'nationality' => '{"ar": "إقليم المحيط الهندي البريطاني", "en": "British Indian Ocean Territory"}', 'dial_code' => '+ '),
            array('code' => 'IQ', 'name' => '{"ar": "العراق", "en": "Iraq"}', 'nationality' => '{"ar": "عراقي", "en": "Iraqi"}', 'dial_code' => '+964'),
            array('code' => 'IR', 'name' => '{"ar": "إيران", "en": "Iran"}', 'nationality' => '{"ar": "إيراني", "en": "Iranian"}', 'dial_code' => '+98'),
            array('code' => 'IS', 'name' => '{"ar": "آيسلندا", "en": "Iceland"}', 'nationality' => '{"ar": "آيسلندي", "en": "Icelandic"}', 'dial_code' => '+354'),
            array('code' => 'IT', 'name' => '{"ar": "إيطاليا", "en": "Italy"}', 'nationality' => '{"ar": "إيطالي", "en": "Italian"}', 'dial_code' => '+39'),
            array('code' => 'JE', 'name' => '{"ar": "جيرزي", "en": "Jersey"}', 'nationality' => '{"ar": "جيرزي", "en": "Jersian"}', 'dial_code' => '+ '),
            array('code' => 'JM', 'name' => '{"ar": "جمايكا", "en": "Jamaica"}', 'nationality' => '{"ar": "جمايكي", "en": "Jamaican"}', 'dial_code' => '+1876'),
            array('code' => 'JO', 'name' => '{"ar": "الأردن", "en": "Jordan"}', 'nationality' => '{"ar": "أردني", "en": "Jordanian"}', 'dial_code' => '+962'),
            array('code' => 'JP', 'name' => '{"ar": "اليابان", "en": "Japan"}', 'nationality' => '{"ar": "ياباني", "en": "Japanese"}', 'dial_code' => '+81'),
            array('code' => 'KE', 'name' => '{"ar": "كينيا", "en": "Kenya"}', 'nationality' => '{"ar": "كيني", "en": "Kenyan"}', 'dial_code' => '+254'),
            array('code' => 'KG', 'name' => '{"ar": "قيرغيزستان", "en": "Kyrgyzstan"}', 'nationality' => '{"ar": "قيرغيزستاني", "en": "Kyrgyzstani"}', 'dial_code' => '+996'),
            array('code' => 'KH', 'name' => '{"ar": "كمبوديا", "en": "Cambodia"}', 'nationality' => '{"ar": "كمبودي", "en": "Cambodian"}', 'dial_code' => '+855'),
            array('code' => 'KI', 'name' => '{"ar": "كيريباتي", "en": "Kiribati"}', 'nationality' => '{"ar": "كيريباتي", "en": "I-Kiribati"}', 'dial_code' => '+686'),
            array('code' => 'KM', 'name' => '{"ar": "جزر القمر", "en": "Comoros"}', 'nationality' => '{"ar": "جزر القمر", "en": "Comorian"}', 'dial_code' => '+269'),
            array('code' => 'KN', 'name' => '{"ar": "سانت كيتس ونيفس,", "en": "Saint Kitts and Nevis"}', 'nationality' => '{"ar": "سانت كيتس ونيفس", "en": "Kittitian/Nevisian"}', 'dial_code' => '+1869'),
            array('code' => 'KP', 'name' => '{"ar": "كوريا الشمالية", "en": "Korea(North Korea)"}', 'nationality' => '{"ar": "كوري", "en": "North Korean"}', 'dial_code' => '+850'),
            array('code' => 'KR', 'name' => '{"ar": "كوريا الجنوبية", "en": "Korea(South Korea)"}', 'nationality' => '{"ar": "كوري", "en": "South Korean"}', 'dial_code' => '+82'),
            array('code' => 'KW', 'name' => '{"ar": "الكويت", "en": "Kuwait"}', 'nationality' => '{"ar": "كويتي", "en": "Kuwaiti"}', 'dial_code' => '+965'),
            array('code' => 'KY', 'name' => '{"ar": "جزر كايمان", "en": "Cayman Islands"}', 'nationality' => '{"ar": "كايماني", "en": "Caymanian"}', 'dial_code' => '+1345'),
            array('code' => 'KZ', 'name' => '{"ar": "كازاخستان", "en": "Kazakhstan"}', 'nationality' => '{"ar": "كازاخستاني", "en": "Kazakh"}', 'dial_code' => '+7'),
            array('code' => 'LA', 'name' => '{"ar": "لاوس", "en": "Lao PDR"}', 'nationality' => '{"ar": "لاوسي", "en": "Laotian"}', 'dial_code' => '+856'),
            array('code' => 'LB', 'name' => '{"ar": "لبنان", "en": "Lebanon"}', 'nationality' => '{"ar": "لبناني", "en": "Lebanese"}', 'dial_code' => '+961'),
            array('code' => 'LC', 'name' => '{"ar": "سان بيير وميكلون", "en": "Saint Pierre and Miquelon"}', 'nationality' => '{"ar": "سان بيير وميكلوني", "en": "St. Pierre and Miquelon"}', 'dial_code' => '+1758'),
            array('code' => 'LI', 'name' => '{"ar": "ليختنشتين", "en": "Liechtenstein"}', 'nationality' => '{"ar": "ليختنشتيني", "en": "Liechtenstein"}', 'dial_code' => '+423'),
            array('code' => 'LK', 'name' => '{"ar": "سريلانكا", "en": "Sri Lanka"}', 'nationality' => '{"ar": "سريلانكي", "en": "Sri Lankian"}', 'dial_code' => '+94'),
            array('code' => 'LR', 'name' => '{"ar": "ليبيريا", "en": "Liberia"}', 'nationality' => '{"ar": "ليبيري", "en": "Liberian"}', 'dial_code' => '+231'),
            array('code' => 'LS', 'name' => '{"ar": "ليسوتو", "en": "Lesotho"}', 'nationality' => '{"ar": "ليوسيتي", "en": "Basotho"}', 'dial_code' => '+266'),
            array('code' => 'LT', 'name' => '{"ar": "لتوانيا", "en": "Lithuania"}', 'nationality' => '{"ar": "لتوانيي", "en": "Lithuanian"}', 'dial_code' => '+370'),
            array('code' => 'LU', 'name' => '{"ar": "لوكسمبورغ", "en": "Luxembourg"}', 'nationality' => '{"ar": "لوكسمبورغي", "en": "Luxembourger"}', 'dial_code' => '+352'),
            array('code' => 'LV', 'name' => '{"ar": "لاتفيا", "en": "Latvia"}', 'nationality' => '{"ar": "لاتيفي", "en": "Latvian"}', 'dial_code' => '+371'),
            array('code' => 'LY', 'name' => '{"ar": "ليبيا", "en": "Libya"}', 'nationality' => '{"ar": "ليبي", "en": "Libyan"}', 'dial_code' => '+218'),
            array('code' => 'MA', 'name' => '{"ar": "المغرب", "en": "Morocco"}', 'nationality' => '{"ar": "مغربي", "en": "Moroccan"}', 'dial_code' => '+212'),
            array('code' => 'MC', 'name' => '{"ar": "موناكو", "en": "Monaco"}', 'nationality' => '{"ar": "مونيكي", "en": "Monacan"}', 'dial_code' => '+377'),
            array('code' => 'MD', 'name' => '{"ar": "مولدافيا", "en": "Moldova"}', 'nationality' => '{"ar": "مولديفي", "en": "Moldovan"}', 'dial_code' => '+373'),
            array('code' => 'ME', 'name' => '{"ar": "الجبل الأسود", "en": "Montenegro"}', 'nationality' => '{"ar": "الجبل الأسود", "en": "Montenegrin"}', 'dial_code' => '+382'),
            array('code' => 'MF', 'name' => '{"ar": "ساينت مارتن فرنسي", "en": "Saint Martin (French part)"}', 'nationality' => '{"ar": "ساينت مارتني فرنسي", "en": "St. Martian(French)"}', 'dial_code' => '+1599'),
            array('code' => 'MG', 'name' => '{"ar": "مدغشقر", "en": "Madagascar"}', 'nationality' => '{"ar": "مدغشقري", "en": "Malagasy"}', 'dial_code' => '+261'),
            array('code' => 'MH', 'name' => '{"ar": "جزر مارشال", "en": "Marshall Islands"}', 'nationality' => '{"ar": "مارشالي", "en": "Marshallese"}', 'dial_code' => '+692'),
            array('code' => 'MK', 'name' => '{"ar": "مقدونيا", "en": "Macedonia"}', 'nationality' => '{"ar": "مقدوني", "en": "Macedonian"}', 'dial_code' => '+389'),
            array('code' => 'ML', 'name' => '{"ar": "مالي", "en": "Mali"}', 'nationality' => '{"ar": "مالي", "en": "Malian"}', 'dial_code' => '+223'),
            array('code' => 'MM', 'name' => '{"ar": "ميانمار", "en": "Myanmar"}', 'nationality' => '{"ar": "ميانماري", "en": "Myanmarian"}', 'dial_code' => '+95'),
            array('code' => 'MN', 'name' => '{"ar": "منغوليا", "en": "Mongolia"}', 'nationality' => '{"ar": "منغولي", "en": "Mongolian"}', 'dial_code' => '+976'),
            array('code' => 'MO', 'name' => '{"ar": "ماكاو", "en": "Macau"}', 'nationality' => '{"ar": "ماكاوي", "en": "Macanese"}', 'dial_code' => '+853'),
            array('code' => 'MP', 'name' => '{"ar": "جزر ماريانا الشمالية", "en": "Northern Mariana Islands"}', 'nationality' => '{"ar": "ماريني", "en": "Northern Marianan"}', 'dial_code' => '+1670'),
            array('code' => 'MQ', 'name' => '{"ar": "مارتينيك", "en": "Martinique"}', 'nationality' => '{"ar": "مارتينيكي", "en": "Martiniquais"}', 'dial_code' => '+ '),
            array('code' => 'MR', 'name' => '{"ar": "موريتانيا", "en": "Mauritania"}', 'nationality' => '{"ar": "موريتانيي", "en": "Mauritanian"}', 'dial_code' => '+222'),
            array('code' => 'MS', 'name' => '{"ar": "مونتسيرات", "en": "Montserrat"}', 'nationality' => '{"ar": "مونتسيراتي", "en": "Montserratian"}', 'dial_code' => '+1664'),
            array('code' => 'MT', 'name' => '{"ar": "مالطا", "en": "Malta"}', 'nationality' => '{"ar": "مالطي", "en": "Maltese"}', 'dial_code' => '+356'),
            array('code' => 'MU', 'name' => '{"ar": "موريشيوس", "en": "Mauritius"}', 'nationality' => '{"ar": "موريشيوسي", "en": "Mauritian"}', 'dial_code' => '+230'),
            array('code' => 'MV', 'name' => '{"ar": "المالديف", "en": "Maldives"}', 'nationality' => '{"ar": "مالديفي", "en": "Maldivian"}', 'dial_code' => '+960'),
            array('code' => 'MW', 'name' => '{"ar": "مالاوي", "en": "Malawi"}', 'nationality' => '{"ar": "مالاوي", "en": "Malawian"}', 'dial_code' => '+265'),
            array('code' => 'MX', 'name' => '{"ar": "المكسيك", "en": "Mexico"}', 'nationality' => '{"ar": "مكسيكي", "en": "Mexican"}', 'dial_code' => '+52'),
            array('code' => 'MY', 'name' => '{"ar": "ماليزيا", "en": "Malaysia"}', 'nationality' => '{"ar": "ماليزي", "en": "Malaysian"}', 'dial_code' => '+60'),
            array('code' => 'MZ', 'name' => '{"ar": "موزمبيق", "en": "Mozambique"}', 'nationality' => '{"ar": "موزمبيقي", "en": "Mozambican"}', 'dial_code' => '+258'),
            array('code' => 'NA', 'name' => '{"ar": "ناميبيا", "en": "Namibia"}', 'nationality' => '{"ar": "ناميبي", "en": "Namibian"}', 'dial_code' => '+264'),
            array('code' => 'NC', 'name' => '{"ar": "كاليدونيا الجديدة", "en": "New Caledonia"}', 'nationality' => '{"ar": "كاليدوني", "en": "New Caledonian"}', 'dial_code' => '+687'),
            array('code' => 'NE', 'name' => '{"ar": "النيجر", "en": "Niger"}', 'nationality' => '{"ar": "نيجيري", "en": "Nigerien"}', 'dial_code' => '+227'),
            array('code' => 'NF', 'name' => '{"ar": "جزيرة نورفولك", "en": "Norfolk Island"}', 'nationality' => '{"ar": "نورفوليكي", "en": "Norfolk Islander"}', 'dial_code' => '+ '),
            array('code' => 'NG', 'name' => '{"ar": "نيجيريا", "en": "Nigeria"}', 'nationality' => '{"ar": "نيجيري", "en": "Nigerian"}', 'dial_code' => '+234'),
            array('code' => 'NI', 'name' => '{"ar": "نيكاراجوا", "en": "Nicaragua"}', 'nationality' => '{"ar": "نيكاراجوي", "en": "Nicaraguan"}', 'dial_code' => '+505'),
            array('code' => 'NL', 'name' => '{"ar": "هولندا", "en": "Netherlands"}', 'nationality' => '{"ar": "هولندي", "en": "Dutch"}', 'dial_code' => '+31'),
            array('code' => 'NO', 'name' => '{"ar": "النرويج", "en": "Norway"}', 'nationality' => '{"ar": "نرويجي", "en": "Norwegian"}', 'dial_code' => '+47'),
            array('code' => 'NP', 'name' => '{"ar": "نيبال", "en": "Nepal"}', 'nationality' => '{"ar": "نيبالي", "en": "Nepalese"}', 'dial_code' => '+977'),
            array('code' => 'NR', 'name' => '{"ar": "نورو", "en": "Nauru"}', 'nationality' => '{"ar": "نوري", "en": "Nauruan"}', 'dial_code' => '+674'),
            array('code' => 'NU', 'name' => '{"ar": "ني", "en": "Niue"}', 'nationality' => '{"ar": "ني", "en": "Niuean"}', 'dial_code' => '+683'),
            array('code' => 'NZ', 'name' => '{"ar": "نيوزيلندا", "en": "New Zealand"}', 'nationality' => '{"ar": "نيوزيلندي", "en": "New Zealander"}', 'dial_code' => '+64'),
            array('code' => 'OM', 'name' => '{"ar": "عمان", "en": "Oman"}', 'nationality' => '{"ar": "عماني", "en": "Omani"}', 'dial_code' => '+968'),
            array('code' => 'PA', 'name' => '{"ar": "بنما", "en": "Panama"}', 'nationality' => '{"ar": "بنمي", "en": "Panamanian"}', 'dial_code' => '+507'),
            array('code' => 'PE', 'name' => '{"ar": "بيرو", "en": "Peru"}', 'nationality' => '{"ar": "بيري", "en": "Peruvian"}', 'dial_code' => '+51'),
            array('code' => 'PF', 'name' => '{"ar": "بولينيزيا الفرنسية", "en": "French Polynesia"}', 'nationality' => '{"ar": "بولينيزيي", "en": "French Polynesian"}', 'dial_code' => '+689'),
            array('code' => 'PG', 'name' => '{"ar": "بابوا غينيا الجديدة", "en": "Papua New Guinea"}', 'nationality' => '{"ar": "بابوي", "en": "Papua New Guinean"}', 'dial_code' => '+675'),
            array('code' => 'PH', 'name' => '{"ar": "الفليبين", "en": "Philippines"}', 'nationality' => '{"ar": "فلبيني", "en": "Filipino"}', 'dial_code' => '+63'),
            array('code' => 'PK', 'name' => '{"ar": "باكستان", "en": "Pakistan"}', 'nationality' => '{"ar": "باكستاني", "en": "Pakistani"}', 'dial_code' => '+92'),
            array('code' => 'PL', 'name' => '{"ar": "بولونيا", "en": "Poland"}', 'nationality' => '{"ar": "بوليني", "en": "Polish"}', 'dial_code' => '+48'),
            array('code' => 'PN', 'name' => '{"ar": "بيتكيرن", "en": "Pitcairn"}', 'nationality' => '{"ar": "بيتكيرني", "en": "Pitcairn Islander"}', 'dial_code' => '+870'),
            array('code' => 'PR', 'name' => '{"ar": "بورتو ريكو", "en": "Puerto Rico"}', 'nationality' => '{"ar": "بورتي", "en": "Puerto Rican"}', 'dial_code' => '+1'),
            array('code' => 'PS', 'name' => '{"ar": "فلسطين", "en": "Palestine"}', 'nationality' => '{"ar": "فلسطيني", "en": "Palestinian"}', 'dial_code' => '+ '),
            array('code' => 'PT', 'name' => '{"ar": "البرتغال", "en": "Portugal"}', 'nationality' => '{"ar": "برتغالي", "en": "Portuguese"}', 'dial_code' => '+351'),
            array('code' => 'PW', 'name' => '{"ar": "بالاو", "en": "Palau"}', 'nationality' => '{"ar": "بالاوي", "en": "Palauan"}', 'dial_code' => '+680'),
            array('code' => 'PY', 'name' => '{"ar": "باراغواي", "en": "Paraguay"}', 'nationality' => '{"ar": "بارغاوي", "en": "Paraguayan"}', 'dial_code' => '+595'),
            array('code' => 'QA', 'name' => '{"ar": "قطر", "en": "Qatar"}', 'nationality' => '{"ar": "قطري", "en": "Qatari"}', 'dial_code' => '+974'),
            array('code' => 'RE', 'name' => '{"ar": "ريونيون", "en": "Reunion Island"}', 'nationality' => '{"ar": "ريونيوني", "en": "Reunionese"}', 'dial_code' => '+ '),
            array('code' => 'RO', 'name' => '{"ar": "رومانيا", "en": "Romania"}', 'nationality' => '{"ar": "روماني", "en": "Romanian"}', 'dial_code' => '+40'),
            array('code' => 'RS', 'name' => '{"ar": "صربيا", "en": "Serbia"}', 'nationality' => '{"ar": "صربي", "en": "Serbian"}', 'dial_code' => '+381'),
            array('code' => 'RU', 'name' => '{"ar": "روسيا", "en": "Russian"}', 'nationality' => '{"ar": "روسي", "en": "Russian"}', 'dial_code' => '+7'),
            array('code' => 'RW', 'name' => '{"ar": "رواندا", "en": "Rwanda"}', 'nationality' => '{"ar": "رواندا", "en": "Rwandan"}', 'dial_code' => '+250'),
            array('code' => 'SA', 'name' => '{"ar": "المملكة العربية السعودية", "en": "Saudi Arabia"}', 'nationality' => '{"ar": "سعودي", "en": "Saudi Arabian"}', 'dial_code' => '+966'),
            array('code' => 'SB', 'name' => '{"ar": "جزر سليمان", "en": "Solomon Islands"}', 'nationality' => '{"ar": "جزر سليمان", "en": "Solomon Island"}', 'dial_code' => '+677'),
            array('code' => 'SC', 'name' => '{"ar": "سيشيل", "en": "Seychelles"}', 'nationality' => '{"ar": "سيشيلي", "en": "Seychellois"}', 'dial_code' => '+248'),
            array('code' => 'SD', 'name' => '{"ar": "السودان", "en": "Sudan"}', 'nationality' => '{"ar": "سوداني", "en": "Sudanese"}', 'dial_code' => '+249'),
            array('code' => 'SE', 'name' => '{"ar": "السويد", "en": "Sweden"}', 'nationality' => '{"ar": "سويدي", "en": "Swedish"}', 'dial_code' => '+46'),
            array('code' => 'SG', 'name' => '{"ar": "سنغافورة", "en": "Singapore"}', 'nationality' => '{"ar": "سنغافوري", "en": "Singaporean"}', 'dial_code' => '+65'),
            array('code' => 'SH', 'name' => '{"ar": "سانت هيلانة", "en": "Saint Helena"}', 'nationality' => '{"ar": "هيلاني", "en": "St. Helenian"}', 'dial_code' => '+290'),
            array('code' => 'SI', 'name' => '{"ar": "سلوفينيا", "en": "Slovenia"}', 'nationality' => '{"ar": "سولفيني", "en": "Slovenian"}', 'dial_code' => '+386'),
            array('code' => 'SJ', 'name' => '{"ar": "سفالبارد ويان ماين", "en": "Svalbard and Jan Mayen"}', 'nationality' => '{"ar": "سفالبارد ويان ماين", "en": "Svalbardian/Jan Mayenian"}', 'dial_code' => '+ '),
            array('code' => 'SK', 'name' => '{"ar": "سلوفاكيا", "en": "Slovakia"}', 'nationality' => '{"ar": "سولفاكي", "en": "Slovak"}', 'dial_code' => '+421'),
            array('code' => 'SL', 'name' => '{"ar": "سيراليون", "en": "Sierra Leone"}', 'nationality' => '{"ar": "سيراليوني", "en": "Sierra Leonean"}', 'dial_code' => '+232'),
            array('code' => 'SM', 'name' => '{"ar": "سان مارينو", "en": "San Marino"}', 'nationality' => '{"ar": "ماريني", "en": "Sammarinese"}', 'dial_code' => '+378'),
            array('code' => 'SN', 'name' => '{"ar": "السنغال", "en": "Senegal"}', 'nationality' => '{"ar": "سنغالي", "en": "Senegalese"}', 'dial_code' => '+221'),
            array('code' => 'SO', 'name' => '{"ar": "الصومال", "en": "Somalia"}', 'nationality' => '{"ar": "صومالي", "en": "Somali"}', 'dial_code' => '+252'),
            array('code' => 'SR', 'name' => '{"ar": "سورينام", "en": "Suriname"}', 'nationality' => '{"ar": "سورينامي", "en": "Surinamese"}', 'dial_code' => '+597'),
            array('code' => 'SS', 'name' => '{"ar": "السودان الجنوبي", "en": "South Sudan"}', 'nationality' => '{"ar": "سوادني جنوبي", "en": "South Sudanese"}', 'dial_code' => '+ '),
            array('code' => 'ST', 'name' => '{"ar": "ساو تومي وبرينسيبي", "en": "Sao Tome and Principe"}', 'nationality' => '{"ar": "ساو تومي وبرينسيبي", "en": "Sao Tomean"}', 'dial_code' => '+239'),
            array('code' => 'SV', 'name' => '{"ar": "إلسلفادور", "en": "El Salvador"}', 'nationality' => '{"ar": "سلفادوري", "en": "Salvadoran"}', 'dial_code' => '+503'),
            array('code' => 'SX', 'name' => '{"ar": "ساينت مارتن هولندي", "en": "Sint Maarten (Dutch part)"}', 'nationality' => '{"ar": "ساينت مارتني هولندي", "en": "St. Martian(Dutch)"}', 'dial_code' => '+ '),
            array('code' => 'SY', 'name' => '{"ar": "سوريا", "en": "Syria"}', 'nationality' => '{"ar": "سوري", "en": "Syrian"}', 'dial_code' => '+963'),
            array('code' => 'SZ', 'name' => '{"ar": "سوازيلند", "en": "Swaziland"}', 'nationality' => '{"ar": "سوازيلندي", "en": "Swazi"}', 'dial_code' => '+268'),
            array('code' => 'TC', 'name' => '{"ar": "جزر توركس وكايكوس", "en": "Turks and Caicos Islands"}', 'nationality' => '{"ar": "جزر توركس وكايكوس", "en": "Turks and Caicos Islands"}', 'dial_code' => '+1649'),
            array('code' => 'TD', 'name' => '{"ar": "تشاد", "en": "Chad"}', 'nationality' => '{"ar": "تشادي", "en": "Chadian"}', 'dial_code' => '+235'),
            array('code' => 'TF', 'name' => '{"ar": "أراض فرنسية جنوبية وأنتارتيكية", "en": "French Southern and Antarctic Lands"}', 'nationality' => '{"ar": "أراض فرنسية جنوبية وأنتارتيكية", "en": "French"}', 'dial_code' => '+ '),
            array('code' => 'TG', 'name' => '{"ar": "توغو", "en": "Togo"}', 'nationality' => '{"ar": "توغي", "en": "Togolese"}', 'dial_code' => '+228'),
            array('code' => 'TH', 'name' => '{"ar": "تايلندا", "en": "Thailand"}', 'nationality' => '{"ar": "تايلندي", "en": "Thai"}', 'dial_code' => '+66'),
            array('code' => 'TJ', 'name' => '{"ar": "طاجيكستان", "en": "Tajikistan"}', 'nationality' => '{"ar": "طاجيكستاني", "en": "Tajikistani"}', 'dial_code' => '+992'),
            array('code' => 'TK', 'name' => '{"ar": "توكيلاو", "en": "Tokelau"}', 'nationality' => '{"ar": "توكيلاوي", "en": "Tokelaian"}', 'dial_code' => '+690'),
            array('code' => 'TL', 'name' => '{"ar": "تيمور الشرقية", "en": "Timor-Leste"}', 'nationality' => '{"ar": "تيموري", "en": "Timor-Lestian"}', 'dial_code' => '+670'),
            array('code' => 'TM', 'name' => '{"ar": "تركمانستان", "en": "Turkmenistan"}', 'nationality' => '{"ar": "تركمانستاني", "en": "Turkmen"}', 'dial_code' => '+993'),
            array('code' => 'TN', 'name' => '{"ar": "تونس", "en": "Tunisia"}', 'nationality' => '{"ar": "تونسي", "en": "Tunisian"}', 'dial_code' => '+216'),
            array('code' => 'TO', 'name' => '{"ar": "تونغا", "en": "Tonga"}', 'nationality' => '{"ar": "تونغي", "en": "Tongan"}', 'dial_code' => '+676'),
            array('code' => 'TR', 'name' => '{"ar": "تركيا", "en": "Turkey"}', 'nationality' => '{"ar": "تركي", "en": "Turkish"}', 'dial_code' => '+90'),
            array('code' => 'TT', 'name' => '{"ar": "ترينيداد وتوباغو", "en": "Trinidad and Tobago"}', 'nationality' => '{"ar": "ترينيداد وتوباغو", "en": "Trinidadian/Tobagonian"}', 'dial_code' => '+1868'),
            array('code' => 'TV', 'name' => '{"ar": "توفالو", "en": "Tuvalu"}', 'nationality' => '{"ar": "توفالي", "en": "Tuvaluan"}', 'dial_code' => '+688'),
            array('code' => 'TW', 'name' => '{"ar": "تايوان", "en": "Taiwan"}', 'nationality' => '{"ar": "تايواني", "en": "Taiwanese"}', 'dial_code' => '+886'),
            array('code' => 'TZ', 'name' => '{"ar": "تنزانيا", "en": "Tanzania"}', 'nationality' => '{"ar": "تنزانيي", "en": "Tanzanian"}', 'dial_code' => '+255'),
            array('code' => 'UA', 'name' => '{"ar": "أوكرانيا", "en": "Ukraine"}', 'nationality' => '{"ar": "أوكراني", "en": "Ukrainian"}', 'dial_code' => '+380'),
            array('code' => 'UG', 'name' => '{"ar": "أوغندا", "en": "Uganda"}', 'nationality' => '{"ar": "أوغندي", "en": "Ugandan"}', 'dial_code' => '+256'),
            array('code' => 'UM', 'name' => '{"ar": "قائمة الولايات والمناطق الأمريكية", "en": "US Minor Outlying Islands"}', 'nationality' => '{"ar": "أمريكي", "en": "US Minor Outlying Islander"}', 'dial_code' => '+ '),
            array('code' => 'US', 'name' => '{"ar": "الولايات المتحدة", "en": "United States"}', 'nationality' => '{"ar": "أمريكي", "en": "American"}', 'dial_code' => '+1'),
            array('code' => 'UY', 'name' => '{"ar": "أورغواي", "en": "Uruguay"}', 'nationality' => '{"ar": "أورغواي", "en": "Uruguayan"}', 'dial_code' => '+598'),
            array('code' => 'UZ', 'name' => '{"ar": "أوزباكستان", "en": "Uzbekistan"}', 'nationality' => '{"ar": "أوزباكستاني", "en": "Uzbek"}', 'dial_code' => '+998'),
            array('code' => 'VA', 'name' => '{"ar": "فنزويلا", "en": "Vatican City"}', 'nationality' => '{"ar": "فاتيكاني", "en": "Vatican"}', 'dial_code' => '+39'),
            array('code' => 'VC', 'name' => '{"ar": "سانت فنسنت وجزر غرينادين", "en": "Saint Vincent and the Grenadines"}', 'nationality' => '{"ar": "سانت فنسنت وجزر غرينادين", "en": "Saint Vincent and the Grenadines"}', 'dial_code' => '+1784'),
            array('code' => 'VE', 'name' => '{"ar": "فنزويلا", "en": "Venezuela"}', 'nationality' => '{"ar": "فنزويلي", "en": "Venezuelan"}', 'dial_code' => '+58'),
            array('code' => 'VI', 'name' => '{"ar": "الجزر العذراء الأمريكي", "en": "Virgin Islands (U.S.)"}', 'nationality' => '{"ar": "أمريكي", "en": "American Virgin Islander"}', 'dial_code' => '+1340'),
            array('code' => 'VN', 'name' => '{"ar": "فيتنام", "en": "Vietnam"}', 'nationality' => '{"ar": "فيتنامي", "en": "Vietnamese"}', 'dial_code' => '+84'),
            array('code' => 'VU', 'name' => '{"ar": "فانواتو", "en": "Vanuatu"}', 'nationality' => '{"ar": "فانواتي", "en": "Vanuatuan"}', 'dial_code' => '+678'),
            array('code' => 'WF', 'name' => '{"ar": "والس وفوتونا", "en": "Wallis and Futuna Islands"}', 'nationality' => '{"ar": "فوتوني", "en": "Wallisian/Futunan"}', 'dial_code' => '+681'),
            array('code' => 'WS', 'name' => '{"ar": "ساموا", "en": "Samoa"}', 'nationality' => '{"ar": "ساموي", "en": "Samoan"}', 'dial_code' => '+685'),
            array('code' => 'XK', 'name' => '{"ar": "كوسوفو", "en": "Kosovo"}', 'nationality' => '{"ar": "كوسيفي", "en": "Kosovar"}', 'dial_code' => '+381'),
            array('code' => 'YE', 'name' => '{"ar": "اليمن", "en": "Yemen"}', 'nationality' => '{"ar": "يمني", "en": "Yemeni"}', 'dial_code' => '+967'),
            array('code' => 'YT', 'name' => '{"ar": "مايوت", "en": "Mayotte"}', 'nationality' => '{"ar": "مايوتي", "en": "Mahoran"}', 'dial_code' => '+262'),
            array('code' => 'ZA', 'name' => '{"ar": "جنوب أفريقيا", "en": "South Africa"}', 'nationality' => '{"ar": "أفريقي", "en": "South African"}', 'dial_code' => '+27'),
            array('code' => 'ZM', 'name' => '{"ar": "زامبيا", "en": "Zambia"}', 'nationality' => '{"ar": "زامبياني", "en": "Zambian"}', 'dial_code' => '+260'),
            array('code' => 'ZW', 'name' => '{"ar": "زمبابوي", "en": "Zimbabwe"}', 'nationality' => '{"ar": "زمبابوي", "en": "Zimbabwean"}', 'dial_code' => '+263')
        );

        foreach ($countries as $country) {
            Country::create([
                'code' => $country['code'],
                'name' => $country['name'],
                'nationality' => $country['nationality'],
                'dial_code' => $country['dial_code']
            ]);
        }
    }
}
